### ISSUE TITLE
Not working on Coda-4582 

### ISSUE THREAD

**Issue by edin702** [hairyhenderson/hitron_coda_exporter#111]
ts=2022-07-29T23:26:04.541Z caller=main.go:176 level=info msg="Listening on" address=:9780
ts=2022-07-29T23:26:34.167Z caller=collector_router.go:123 level=error msg="Error scraping RouterSysInfo" err="J                     SON decoding failed: failed to unmarshal RouterSysInfo \"{\\\"errCode\\\":\\\"000\\\",\\\"errMsg\\\":\\\"\\\",\\                     \"deviceId\\\":\\\"\\\",\\\"modelName\\\":\\\"CODA-4582\\\",\\\"vendorName\\\":\\\"RES\\\",\\\"                     SerialNum\\\":\\\"\\\",\\\"HwVersion\\\":\\\"2A\\\",\\\"ApiVersion\\\":\\\"1.12.1\\\",\\\"SoftwareVe                     rsion\\\":\\\"7.1.1.2.8b4\\\",\\\"deploymentName\\\":\\\"\\\",\\\"VendorLogo\\\":\\\"0\\\",\\\"sysTime\\\":\\\"2                     022-07-29 23:26:32\\\",\\\"tz\\\":\\\"0\\\",\\\"lanName\\\":null,\\\"privLanIP\\\":\\\"192.168.0.1\\\\/24\\\",\\                     \"lanRx\\\":\\\"1.05G Bytes\\\",\\\"lanTx\\\":\\\"18.15G Bytes\\\",\\\"wanName\\\":null,\\\"wanIP\\\":[\\\"0.0.0                     .0\\\\n\\\",\\\"\\\"],\\\"wanRx\\\":\\\"18.23G Bytes\\\",\\\"wanRxPkts\\\":null,\\\"wanTx\\\":\\\"989.1M Bytes\\                     \",\\\"wanTxPkts\\\":null,\\\"dns\\\":[\\\"\\\",\\\"\\\"],\\\"rfMac\\\":\\\"\\\",\\\"secDNS\\\"                     :\\\"none\\\",\\\"systemLanUptime\\\":\\\"000 days 04h:43m:05s\\\",\\\"systemWanUptime\\\":\\\"000 days 00h:00m:                     00s\\\",\\\"routerMode\\\":\\\"Bridge\\\",\\\"lanAsWanMode\\\":\\\"0\\\",\\\"privLanIp\\\":\\\"192.168.0.1\\\\/2                     4\\\"}\": invalid IP address: 0.0.0.0\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=]

Not sure if this is related to bridge mode being enabled or not

**Comment by edin702** [comment]
Not sure if this is related with it being in bridge mode or not

**Comment by hairyhenderson** [comment]
> Not sure if this is related to bridge mode being enabled or not

Perhaps! The message `invalid IP address` seems a bit odd though - `0.0.0.0` _is_ a valid address, in terms of parsing at any rate.

Ah, looking closer at the JSON it looks like the `wanIP` value is `[ "0.0.0.0\n", "" ]`, which is incorrect. There's an errant `\n` in there, and the second element is empty for some reason.

It _should_ be fairly straightforward to loosen the parsing to strip the `\n` and ignore the empty values.

There's another issue though - it looks like some of the numeric values are formatted differently - like `"lanTx": "18.15G Bytes"`, which on the CODA-4680 just numeric bytes (like `"lanTx":"141585555187"`). That's probably not too difficult to parse though. There's already a custom parsing function for the `RouterSysInfo` type ([here](https://github.com/hairyhenderson/hitron_coda/blob/main/router_types.go#L145)), so it's not too complicated to tweaked it further.

One logistical challenge with fixing this is that I'm no longer actually using this exporter because I switched to a fibre connection a couple months back (I'm actually just about to list my CODA-4680 on eBay). So that means that I'll need your help testing the fix.

Also, the library that handles this is in a different repo - https://github.com/hairyhenderson/hitron_coda - but it does have a CLI that can be used for direct access without involving the Prometheus exporter (as an aside - I don't remember _why_ I split it this way... in retrospect I probably should've kept it all in one repo for simplicity!).

Anyway, I'll probably tag you in the PR on the other repo and ask you to help test it out, if you're willing to iterate on this a bit!

**Comment by hairyhenderson** [comment]
FYI I've issued https://github.com/hairyhenderson/hitron_coda/pull/28 to get past this issue.

**Comment by hairyhenderson** [comment]
@edin702 https://github.com/hairyhenderson/hitron_coda_exporter/pull/112 should fix this error. Once that merges a new image will be built, or you can build a new binary instead!

Please let me know if you run into further issues!

**Comment by edin702** [comment]
Thank you so much! Its now working and got it graphing in Grafana!
